repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        language: system
        entry: bash -c "PYTHONPATH=$(pwd)/src:$PYTHONPATH pipenv run mypy --config-file ./mypy.ini ."
        pass_filenames: false
        verbose: true
        types: [ "python" ]
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: pipenv run python src/manage.py makemigrations --check
        language: system
        types: [ python ]
        pass_filenames: false
        require_serial: true
  - repo: local
    hooks:
      - id: pre-commit-spectacular-schema-validate
        name: Validate schema of API
        entry: poetry run python src/manage.py spectacular --file schema.yaml --validate --fail-on-warn
        language: system
        types: [ python ]
        pass_filenames: false
        require_serial: true
